services:
  jenkins:
    image: my-jenkins:latest   # <-- свой собранный образ (на базе jenkins/jenkins:lts-jdk17 с docker-ce-cli)
    container_name: jenkins-docker
    restart: unless-stopped
    user: root
    ports:
      - "9696:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init.groovy.d:/usr/share/jenkins/ref/init.groovy.d:ro