services:
  jenkins:
    image: sushant032/jenkins-docker:latest
    privileged: true
    restart: unless-stopped
    user: root
    ports:
      - 9696:8080
      - 50000:50000
    container_name: docker-jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init.groovy.d:/usr/share/jenkins/ref/init.groovy.d:ro